apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm.fullname" . }}-sec
  labels:
    {{- include "helm.labels" . | nindent 4 }}
type: Opaque
data:
  WEATHER_API_KEY: {{ .Values.appSecrets.WEATHER_API_KEY | b64enc }}
