replicaCount: 1

image:
  repository: sat599/demo-app
  pullPolicy: IfNotPresent
  tag: "v1.0.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

securityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroupChangePolicy: "OnRootMismatch"


appConfig:
  APP_PORT: "3000"
  WEATHER_API_BASEPATH: http://www.7timer.info

appSecrets:
  WEATHER_API_KEY: secret_api_key

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/group.name: demo-app-ingress-group
    alb.ingress.kubernetes.io/ssl-redirect: '443'
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix


resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi


nodeSelector: {}

tolerations: []

affinity: {}
