name: Build & Publish Image to Dockerhub

on:
  push:
    tags:
      - "v*"

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Set tag as release version
        run: echo $GITHUB_REF | grep -oP 'refs/tags/\K.*' | sed 's/^/RELEASE_VERSION=/' >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/demo-app:${{ env.RELEASE_VERSION }}
      
      - name: Publish helm
        uses: peymanmortazavi/eks-helm-deploy@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS__KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          cluster-name: demo-cluster
          config-files: helm/values.yaml
          namespace: dev
          values: image.tag=${{ env.RELEASE_VERSION }},appSecrets.WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }}
          name: release_${{ env.RELEASE_VERSION }}
